# Generated by Django 4.1.3 on 2022-11-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(default='9999999', max_length=15, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='account',
            name='worker',
            field=models.CharField(choices=[('applicant', 'Соискатель'), ('employer', 'Работодатель')], default='applicant', max_length=30, verbose_name='Тип'),
        ),
    ]
