# Generated by Django 4.1.3 on 2022-11-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='worker',
        ),
        migrations.AddField(
            model_name='account',
            name='is_worker',
            field=models.BooleanField(default=True, verbose_name='Соискатель'),
        ),
    ]
