# Generated by Django 4.1.3 on 2022-11-22 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='publication',
            field=models.BooleanField(default=False, verbose_name='Будет опубликовано'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_resume', to=settings.AUTH_USER_MODEL, verbose_name='Автор резюме'),
        ),
    ]
