# Generated by Django 4.1.3 on 2022-11-25 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0002_resume_publication_alter_resume_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор резюме'),
        ),
    ]
